language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2.2.3 # Travis CI build fails with 2.2.4
  - rbx # Travis CI build fails with 2.2.4
env: API_URL=https://store-vnh06c71.mybigcommerce.com API_USER=admin API_PASS=123456

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx # Travis CI build fails with 2.2.4
