version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  ruby: bigcommerce/internal-ruby@volatile

defaults: &defaults
  notify_failure: false

ruby_2_7_defaults: &ruby_2_7_defaults
  <<: *defaults
  e:
    name: ruby/ruby
    ruby-version: '2.7'

ruby_3_0_defaults: &ruby_3_0_defaults
  <<: *defaults
  e:
    name: ruby/ruby
    ruby-version: '3.0'

ruby_3_1_defaults: &ruby_3_1_defaults
  <<: *defaults
  e:
    name: ruby/ruby
    ruby-version: '3.1'

ruby_3_2_defaults: &ruby_3_2_defaults
  <<: *defaults
  e:
    name: ruby/ruby
    ruby-version: '3.2'

workflows:
  version: 2
  ruby_2_7:
    jobs:
      - ruby/bundle-audit:
          <<: *ruby_2_7_defaults
          name: ruby-2_7-bundle_audit
      - ruby/rubocop:
          <<: *ruby_2_7_defaults
          name: ruby-2_7-rubocop
      - ruby/rspec-unit:
          <<: *ruby_2_7_defaults
          name: ruby-2_7-rspec_unit
          db: false
          code-climate: false
  ruby_3_0:
    jobs:
      - ruby/bundle-audit:
          <<: *ruby_3_0_defaults
          name: ruby-3_0-bundle_audit
      - ruby/rubocop:
          <<: *ruby_3_0_defaults
          name: ruby-3_0-rubocop
      - ruby/rspec-unit:
          <<: *ruby_3_0_defaults
          name: ruby-3_0-rspec_unit
          db: false
  ruby_3_1:
    jobs:
      - ruby/bundle-audit:
          <<: *ruby_3_1_defaults
          name: ruby-3_1-bundle_audit
      - ruby/rubocop:
          <<: *ruby_3_1_defaults
          name: ruby-3_1-rubocop
      - ruby/rspec-unit:
          <<: *ruby_3_1_defaults
          name: ruby-3_1-rspec_unit
          db: false
          code-climate: false
  ruby_3_2:
    jobs:
      - ruby/bundle-audit:
          <<: *ruby_3_2_defaults
          name: ruby-3_2-bundle_audit
      - ruby/rubocop:
          <<: *ruby_3_2_defaults
          name: ruby-3_2-rubocop
      - ruby/rspec-unit:
          <<: *ruby_3_2_defaults
          name: ruby-3_2-rspec_unit
          db: false
          code-climate: false
